services:
  - type: web
    name: taskmanager-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: static
    name: taskmanager-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    rootDir: frontend/vite-project
